name: Deploy

on:
   push:
      branches:
         - main

jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Create docker with repo
           uses: actions/checkout@v2
         # Setup key in docker
         - run: set -eu
         - run: mkdir "$HOME/.ssh"
         - run: echo "${{ secrets.KEY }}" > "$HOME/.ssh/key"
         - run: chmod 600 "$HOME/.ssh/key"
         # Copy substructure from prod folder to hosting
         - run: cd prod && rsync -e "ssh -p ${{ secrets.PORT }} -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ secrets.USER }}@${{ secrets.HOST }}:/home/${{ secrets.USER }}/elenivan.ru/htdocs/web-dev-html-css
